[package]
name = "terscii"
version = "0.1.0"
edition = "2024"
description = "The Ternary Standard Code for Information Exchange"

[dependencies]
ternary = { path = "../ternary" }
septivigntimal = { path = "../septivigntimal" }
