use ternary::trits::Trit;
pub use ternary::trits::Trit::*;
pub use septivigntimal::*;

/// POne is 27 trit, NOne is 9 trit
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct Register(pub [Trit; 3]);
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct RegisterSized(pub Trit, pub [Trit; 3]);

pub const R13:  RegisterSized = RegisterSized(POne, M);
pub const R12:  RegisterSized = RegisterSized(POne, L);
pub const R11:  RegisterSized = RegisterSized(POne, K);
pub const R10:  RegisterSized = RegisterSized(POne, J);
pub const R9:   RegisterSized = RegisterSized(POne, I);
pub const R8:   RegisterSized = RegisterSized(POne, H);
pub const R7:   RegisterSized = RegisterSized(POne, G);
pub const R6:   RegisterSized = RegisterSized(POne, F);
pub const R5:   RegisterSized = RegisterSized(POne, E);
pub const R4:   RegisterSized = RegisterSized(POne, D);
pub const R3:   RegisterSized = RegisterSized(POne, C);
pub const R2:   RegisterSized = RegisterSized(POne, B);
pub const R1:   RegisterSized = RegisterSized(POne, A);
pub const R0:   RegisterSized = RegisterSized(POne, ZERO);
pub const RN1:  RegisterSized = RegisterSized(POne, N);
pub const RN2:  RegisterSized = RegisterSized(POne, O);
pub const RN3:  RegisterSized = RegisterSized(POne, P);
pub const RN4:  RegisterSized = RegisterSized(POne, Q);
pub const RN5:  RegisterSized = RegisterSized(POne, R);
pub const RN6:  RegisterSized = RegisterSized(POne, S);
pub const RN7:  RegisterSized = RegisterSized(POne, T);
pub const RN8:  RegisterSized = RegisterSized(POne, U);
pub const RN9:  RegisterSized = RegisterSized(POne, V);
pub const RN10: RegisterSized = RegisterSized(POne, W);
pub const RN11: RegisterSized = RegisterSized(POne, X);
pub const RN12: RegisterSized = RegisterSized(POne, Y);
pub const RN13: RegisterSized = RegisterSized(POne, Z);

pub const T13:  RegisterSized = RegisterSized(NOne, M);
pub const T12:  RegisterSized = RegisterSized(NOne, L);
pub const T11:  RegisterSized = RegisterSized(NOne, K);
pub const T10:  RegisterSized = RegisterSized(NOne, J);
pub const T9:   RegisterSized = RegisterSized(NOne, I);
pub const T8:   RegisterSized = RegisterSized(NOne, H);
pub const T7:   RegisterSized = RegisterSized(NOne, G);
pub const T6:   RegisterSized = RegisterSized(NOne, F);
pub const T5:   RegisterSized = RegisterSized(NOne, E);
pub const T4:   RegisterSized = RegisterSized(NOne, D);
pub const T3:   RegisterSized = RegisterSized(NOne, C);
pub const T2:   RegisterSized = RegisterSized(NOne, B);
pub const T1:   RegisterSized = RegisterSized(NOne, A);
pub const T0:   RegisterSized = RegisterSized(NOne, ZERO);
pub const TN1:  RegisterSized = RegisterSized(NOne, N);
pub const TN2:  RegisterSized = RegisterSized(NOne, O);
pub const TN3:  RegisterSized = RegisterSized(NOne, P);
pub const TN4:  RegisterSized = RegisterSized(NOne, Q);
pub const TN5:  RegisterSized = RegisterSized(NOne, R);
pub const TN6:  RegisterSized = RegisterSized(NOne, S);
pub const TN7:  RegisterSized = RegisterSized(NOne, T);
pub const TN8:  RegisterSized = RegisterSized(NOne, U);
pub const TN9:  RegisterSized = RegisterSized(NOne, V);
pub const TN10: RegisterSized = RegisterSized(NOne, W);
pub const TN11: RegisterSized = RegisterSized(NOne, X);
pub const TN12: RegisterSized = RegisterSized(NOne, Y);
pub const TN13: RegisterSized = RegisterSized(NOne, Z);

pub const N13:  Register = Register(M);
pub const N12:  Register = Register(L);
pub const N11:  Register = Register(K);
pub const N10:  Register = Register(J);
pub const N9:   Register = Register(I);
pub const N8:   Register = Register(H);
pub const N7:   Register = Register(G);
pub const N6:   Register = Register(F);
pub const N5:   Register = Register(E);
pub const N4:   Register = Register(D);
pub const N3:   Register = Register(C);
pub const N2:   Register = Register(B);
pub const N1:   Register = Register(A);
pub const N0:   Register = Register(ZERO);
pub const NN1:  Register = Register(N);
pub const NN2:  Register = Register(O);
pub const NN3:  Register = Register(P);
pub const NN4:  Register = Register(Q);
pub const NN5:  Register = Register(R);
pub const NN6:  Register = Register(S);
pub const NN7:  Register = Register(T);
pub const NN8:  Register = Register(U);
pub const NN9:  Register = Register(V);
pub const NN10: Register = Register(W);
pub const NN11: Register = Register(X);
pub const NN12: Register = Register(Y);
pub const NN13: Register = Register(Z);
